//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_C____.WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="WS.WSAndroid")]
    public interface WSAndroid {
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSAndroid/retornaLivroRequest", ReplyAction="http://ws/WSAndroid/retornaLivroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WS_C____.WS.retornaLivroResponse retornaLivro(WS_C____.WS.retornaLivroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSAndroid/retornaLivroRequest", ReplyAction="http://ws/WSAndroid/retornaLivroResponse")]
        System.Threading.Tasks.Task<WS_C____.WS.retornaLivroResponse> retornaLivroAsync(WS_C____.WS.retornaLivroRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSAndroid/somaRequest", ReplyAction="http://ws/WSAndroid/somaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WS_C____.WS.somaResponse soma(WS_C____.WS.somaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSAndroid/somaRequest", ReplyAction="http://ws/WSAndroid/somaResponse")]
        System.Threading.Tasks.Task<WS_C____.WS.somaResponse> somaAsync(WS_C____.WS.somaRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSAndroid/helloRequest", ReplyAction="http://ws/WSAndroid/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WS_C____.WS.helloResponse hello(WS_C____.WS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSAndroid/helloRequest", ReplyAction="http://ws/WSAndroid/helloResponse")]
        System.Threading.Tasks.Task<WS_C____.WS.helloResponse> helloAsync(WS_C____.WS.helloRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSAndroid/retornaListaRequest", ReplyAction="http://ws/WSAndroid/retornaListaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WS_C____.WS.retornaListaResponse retornaLista(WS_C____.WS.retornaListaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSAndroid/retornaListaRequest", ReplyAction="http://ws/WSAndroid/retornaListaResponse")]
        System.Threading.Tasks.Task<WS_C____.WS.retornaListaResponse> retornaListaAsync(WS_C____.WS.retornaListaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class livro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anoField;
        
        private string editoraField;
        
        private string nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ano {
            get {
                return this.anoField;
            }
            set {
                this.anoField = value;
                this.RaisePropertyChanged("ano");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string editora {
            get {
                return this.editoraField;
            }
            set {
                this.editoraField = value;
                this.RaisePropertyChanged("editora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaLivro", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class retornaLivroRequest {
        
        public retornaLivroRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaLivroResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class retornaLivroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WS_C____.WS.livro @return;
        
        public retornaLivroResponse() {
        }
        
        public retornaLivroResponse(WS_C____.WS.livro @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="soma", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class somaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double num1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double num2;
        
        public somaRequest() {
        }
        
        public somaRequest(double num1, double num2) {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="somaResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class somaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public somaResponse() {
        }
        
        public somaResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaLista", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class retornaListaRequest {
        
        public retornaListaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class retornaListaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WS_C____.WS.livro[] @return;
        
        public retornaListaResponse() {
        }
        
        public retornaListaResponse(WS_C____.WS.livro[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSAndroidChannel : WS_C____.WS.WSAndroid, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSAndroidClient : System.ServiceModel.ClientBase<WS_C____.WS.WSAndroid>, WS_C____.WS.WSAndroid {
        
        public WSAndroidClient() {
        }
        
        public WSAndroidClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSAndroidClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAndroidClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAndroidClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_C____.WS.retornaLivroResponse WS_C____.WS.WSAndroid.retornaLivro(WS_C____.WS.retornaLivroRequest request) {
            return base.Channel.retornaLivro(request);
        }
        
        public WS_C____.WS.livro retornaLivro() {
            WS_C____.WS.retornaLivroRequest inValue = new WS_C____.WS.retornaLivroRequest();
            WS_C____.WS.retornaLivroResponse retVal = ((WS_C____.WS.WSAndroid)(this)).retornaLivro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_C____.WS.retornaLivroResponse> WS_C____.WS.WSAndroid.retornaLivroAsync(WS_C____.WS.retornaLivroRequest request) {
            return base.Channel.retornaLivroAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_C____.WS.retornaLivroResponse> retornaLivroAsync() {
            WS_C____.WS.retornaLivroRequest inValue = new WS_C____.WS.retornaLivroRequest();
            return ((WS_C____.WS.WSAndroid)(this)).retornaLivroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_C____.WS.somaResponse WS_C____.WS.WSAndroid.soma(WS_C____.WS.somaRequest request) {
            return base.Channel.soma(request);
        }
        
        public double soma(double num1, double num2) {
            WS_C____.WS.somaRequest inValue = new WS_C____.WS.somaRequest();
            inValue.num1 = num1;
            inValue.num2 = num2;
            WS_C____.WS.somaResponse retVal = ((WS_C____.WS.WSAndroid)(this)).soma(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_C____.WS.somaResponse> WS_C____.WS.WSAndroid.somaAsync(WS_C____.WS.somaRequest request) {
            return base.Channel.somaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_C____.WS.somaResponse> somaAsync(double num1, double num2) {
            WS_C____.WS.somaRequest inValue = new WS_C____.WS.somaRequest();
            inValue.num1 = num1;
            inValue.num2 = num2;
            return ((WS_C____.WS.WSAndroid)(this)).somaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_C____.WS.helloResponse WS_C____.WS.WSAndroid.hello(WS_C____.WS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            WS_C____.WS.helloRequest inValue = new WS_C____.WS.helloRequest();
            inValue.name = name;
            WS_C____.WS.helloResponse retVal = ((WS_C____.WS.WSAndroid)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_C____.WS.helloResponse> WS_C____.WS.WSAndroid.helloAsync(WS_C____.WS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_C____.WS.helloResponse> helloAsync(string name) {
            WS_C____.WS.helloRequest inValue = new WS_C____.WS.helloRequest();
            inValue.name = name;
            return ((WS_C____.WS.WSAndroid)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_C____.WS.retornaListaResponse WS_C____.WS.WSAndroid.retornaLista(WS_C____.WS.retornaListaRequest request) {
            return base.Channel.retornaLista(request);
        }
        
        public WS_C____.WS.livro[] retornaLista() {
            WS_C____.WS.retornaListaRequest inValue = new WS_C____.WS.retornaListaRequest();
            WS_C____.WS.retornaListaResponse retVal = ((WS_C____.WS.WSAndroid)(this)).retornaLista(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_C____.WS.retornaListaResponse> WS_C____.WS.WSAndroid.retornaListaAsync(WS_C____.WS.retornaListaRequest request) {
            return base.Channel.retornaListaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_C____.WS.retornaListaResponse> retornaListaAsync() {
            WS_C____.WS.retornaListaRequest inValue = new WS_C____.WS.retornaListaRequest();
            return ((WS_C____.WS.WSAndroid)(this)).retornaListaAsync(inValue);
        }
    }
}
